version: 0.2
phases:
  install:
    runtime-versions:
        java: openjdk8
        python: 3.7
    commands:
      - pip install --upgrade 'pyyaml < 6.0'
      - pip install --upgrade 'six==1.15.0'
      - pip install boto3 --upgrade
      - pip install --upgrade 'docker~=4.0'
      - pip install --upgrade 'aws-sam-translator==1.22.0'
      - pip install pre-commit cloudformation-cli-java-plugin
  build:
    commands:
      - pre-commit run --all-files
      - cd "$CODEBUILD_SRC_DIR/aws-identitystore-common"
      - mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B clean verify install --no-transfer-progress
      - cd "$CODEBUILD_SRC_DIR/aws-identitystore-group"
      - mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B clean verify --no-transfer-progress
    finally:
      - cat "$CODEBUILD_SRC_DIR/aws-identitystore-group/rpdk.log"
