version: 0.2
phases:
  install:
    runtime-versions:
        java: openjdk8
        python: 3.7
    commands:
      - pip install --upgrade 'six==1.16.0'
      - pip install pre-commit cloudformation-cli-java-plugin
      - pip install pyyaml --upgrade
      - pip install boto3 --upgrade
  build:
    commands:
      - pre-commit run --all-files
      - cd "$CODEBUILD_SRC_DIR"
      - cd "aws-identitystore-common"
      - mvn clean verify --no-transfer-progress
      - cd "aws-identitystore-group"
      - mvn clean verify --no-transfer-progress
